print("This program calculates the energy based on a mass input")
print("--------------------")
M = int(input("Enter M:"))
print("--------------------")
print("The mass is", M)
C = 299792458
print("--------------------")
E = (M * C**2)
print("The energy based on a mass input is", E)
print("====================")
